Repository suzuki-shunsuke/release-js-action, pull requests merged in 2025-01, with the labels that each got.

#76 fix: fix base branch
  README.md
  action.yaml
Labels: bug

#109 feat: add an input github_token
  action.yaml
Labels: enhancement

#110 docs: adding section about GitHub Enterprise to README
  README.md
Labels: documentation
